---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: clamav-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs
  type: gp2
  encrypted: "false"


