apiVersion: kustomize.config.k8s.io/v1beta1
namespace: clamav
kind: Kustomization
resources:
  - 0_storage_class.yaml
  - 1_namespace.yaml
  - 2_stateful_set.yaml
  - 3_rest_api.yaml
  - 4_services.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: clamav-configmap
    files:
      - clamd.conf
      - freshclam.conf

images:
  - name: clamav
    newName: docker.io/unbreakab1e/clamav-server
    newTag: 0.0.1
